FROM mongo


COPY ./data/init-users.sh /docker-entrypoint-initdb.d/init-users.sh
COPY ./data/seed.sh /docker-entrypoint-initdb.d/seed.sh
COPY ./data/restaurant.json ./data/restaurant.json

EXPOSE 27017

CMD ["mongod"]
