apiVersion: v1
kind: Service
metadata:
  name: app-python-challenge
  namespace: realchallenge
spec:
  selector:
    app: app-python-challenge
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  type: NodePort
---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: realchallenge
spec:
  selector:
    app: mongodb
  ports:
  - protocol: "TCP"
    port: 27017
    targetPort: 27017
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-python-challenge
  namespace: realchallenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-python-challenge
  template:
    metadata:
      labels:
        app: app-python-challenge
    spec:
      imagePullSecrets:
        - name: githubregistry  
      containers:
        - name: app-python
          image: docker.pkg.github.com/vittyx/the-real-devops-challenge/app-challenge:latest
          env:
            - name: MONGO_URI
              value: mongodb://root:example@mongodb-svc:27017/prueba?authSource=admin 
          ports:
            - containerPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: realchallenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.4
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: root
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: example
          - name: MONGO_INITDB_DATABASE
            value: prueba
        ports:
          - containerPort: 27017
